// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACmoWPmsuoLE66yg9_5g3jUx51u800-1E',
    appId: '1:426339021725:web:008ab97149a67526733574',
    messagingSenderId: '426339021725',
    projectId: 'kiot-b4a41',
    authDomain: 'kiot-b4a41.firebaseapp.com',
    databaseURL: 'https://kiot-b4a41-default-rtdb.firebaseio.com',
    storageBucket: 'kiot-b4a41.firebasestorage.app',
    measurementId: 'G-8D8SQEBPN5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_bRayiVByIfNwDHbfh08-W3zU9z-Nsdo',
    appId: '1:426339021725:android:c680cae07169cb9b733574',
    messagingSenderId: '426339021725',
    projectId: 'kiot-b4a41',
    databaseURL: 'https://kiot-b4a41-default-rtdb.firebaseio.com',
    storageBucket: 'kiot-b4a41.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPhk2BtfIX9sXt2z4tgByPDW-hjMS0Clg',
    appId: '1:426339021725:ios:79faf824c3d70af9733574',
    messagingSenderId: '426339021725',
    projectId: 'kiot-b4a41',
    databaseURL: 'https://kiot-b4a41-default-rtdb.firebaseio.com',
    storageBucket: 'kiot-b4a41.firebasestorage.app',
    iosBundleId: 'com.example.kiotOrder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPhk2BtfIX9sXt2z4tgByPDW-hjMS0Clg',
    appId: '1:426339021725:ios:79faf824c3d70af9733574',
    messagingSenderId: '426339021725',
    projectId: 'kiot-b4a41',
    databaseURL: 'https://kiot-b4a41-default-rtdb.firebaseio.com',
    storageBucket: 'kiot-b4a41.firebasestorage.app',
    iosBundleId: 'com.example.kiotOrder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACmoWPmsuoLE66yg9_5g3jUx51u800-1E',
    appId: '1:426339021725:web:715798dcbb2b1fe9733574',
    messagingSenderId: '426339021725',
    projectId: 'kiot-b4a41',
    authDomain: 'kiot-b4a41.firebaseapp.com',
    databaseURL: 'https://kiot-b4a41-default-rtdb.firebaseio.com',
    storageBucket: 'kiot-b4a41.firebasestorage.app',
    measurementId: 'G-DH2648V2KY',
  );
}
